### ISSUE TITLE
2024.10 update

### ISSUE THREAD

**Issue by cigix** [TrustInSoft/training-examples#2]
* `level2/1_slevel/1_init_buffer.c`: No more false alarm thanks to initial unroll. Need to find a different example for loss of precision on a loop, or deactivate initial unroll.
  * Could be merged or replaced with `level2/1_slevel/3_loop.c`.

AFAICT this is the only file that has to change.

**Comment by pascal-cuoq** [comment]
It's easy to disable initial unrolling in an example. For instance it will not unroll the loop if the modified example below is analyzed with default level2 options:
```
#include <stdio.h>
#include <stdlib.h>
#define SIZ 42
int main(void) {
    char* buffer = malloc(SIZ);
    if (!buffer) abort();
    for (int i = 0; i < SIZ; i++) {
        buffer[i] = i;
    }
    printf("%d\n", buffer[10]);
}
